# RDMA client-server application sample config

sample:
  # Off:0 Trace:1 Debug:2 Info:3 Warning:4 Error:5 Critical:6
  log-level: 3

server:
  device: "mlx5_0"
  ipv4: "192.168.88.20"
  port: 12345

client:
  device: "mlx5_0"